language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  global:
  - VERSION="12.0" LINT_CHECK="0" TESTS="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - if [ "$LINT_CHECK" != "1" ] ; then ln -s ${HOME}/dependencies/server-env/server_environment_files_sample ${HOME}/dependencies/server-env/server_environment_files; fi
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  - travis_after_test_success

branches:
  except:
    - /^merge-branch-.*$/
