sudo: false
language: python

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial

python:
  - '2.7'

virtualenv:
  system_site_packages: true

env:
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="cloud_platform_ovh"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="cloud_platform_ovh"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="cloud_platform,cloud_platform_ovh,cloud_platform_exoscale"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="cloud_platform,cloud_platform_ovh,cloud_platform_exoscale"
  global:
  - VERSION="10.0" LINT_CHECK="0" TESTS="0"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - if [ "$LINT_CHECK" != "1" ] ; then ln -s ${HOME}/dependencies/server-tools/server_environment_files_sample ${HOME}/dependencies/server-tools/server_environment_files; fi
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

services:
  - postgresql

script:
  - travis_run_tests

after_success:
  - travis_after_test_success
